### PR TITLE
Fix link file access denied during system restart

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Bugzilla: 1659678
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@nthomas-redhat @shtripat @mbukatov @GowthamShanmugam

**Review by shtripat — COMMENTED** [review]
Can you add description in commit message regarding why this change is required?

**Comment by GowthamShanmugam** [comment]
i took this and verified it works fine

**Comment by shtripat** [comment]
@GowthamShanmugam I understand this is nothing to do your PR for tendrl-ansible regarding `/var/log/graphite-web` permissions?

**Comment by GowthamShanmugam** [comment]
@shtripat yes

**Comment by GowthamShanmugam** [comment]
LGTM

**Review by cybernth — APPROVED** [review]

**Pull request merged**
